// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mangahub.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genres        []string               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,6,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,8,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_mangahub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Manga) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manga) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type LibraryEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId        string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	CurrentChapter int32                  `protobuf:"varint,4,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	CurrentVolume  int32                  `protobuf:"varint,5,opt,name=current_volume,json=currentVolume,proto3" json:"current_volume,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Rating         int32                  `protobuf:"varint,7,opt,name=rating,proto3" json:"rating,omitempty"`
	Notes          string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LibraryEntry) Reset() {
	*x = LibraryEntry{}
	mi := &file_mangahub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryEntry) ProtoMessage() {}

func (x *LibraryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryEntry.ProtoReflect.Descriptor instead.
func (*LibraryEntry) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{1}
}

func (x *LibraryEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LibraryEntry) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *LibraryEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LibraryEntry) GetCurrentChapter() int32 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *LibraryEntry) GetCurrentVolume() int32 {
	if x != nil {
		return x.CurrentVolume
	}
	return 0
}

func (x *LibraryEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LibraryEntry) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *LibraryEntry) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ProgressResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Entry           *LibraryEntry          `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	PreviousChapter int32                  `protobuf:"varint,2,opt,name=previous_chapter,json=previousChapter,proto3" json:"previous_chapter,omitempty"`
	PreviousVolume  int32                  `protobuf:"varint,3,opt,name=previous_volume,json=previousVolume,proto3" json:"previous_volume,omitempty"`
	TotalChapters   int32                  `protobuf:"varint,4,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	MangaTitle      string                 `protobuf:"bytes,5,opt,name=manga_title,json=mangaTitle,proto3" json:"manga_title,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProgressResult) Reset() {
	*x = ProgressResult{}
	mi := &file_mangahub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResult) ProtoMessage() {}

func (x *ProgressResult) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResult.ProtoReflect.Descriptor instead.
func (*ProgressResult) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressResult) GetEntry() *LibraryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *ProgressResult) GetPreviousChapter() int32 {
	if x != nil {
		return x.PreviousChapter
	}
	return 0
}

func (x *ProgressResult) GetPreviousVolume() int32 {
	if x != nil {
		return x.PreviousVolume
	}
	return 0
}

func (x *ProgressResult) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *ProgressResult) GetMangaTitle() string {
	if x != nil {
		return x.MangaTitle
	}
	return ""
}

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_mangahub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{3}
}

func (x *GetMangaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaResponse) Reset() {
	*x = MangaResponse{}
	mi := &file_mangahub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaResponse) ProtoMessage() {}

func (x *MangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaResponse.ProtoReflect.Descriptor instead.
func (*MangaResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{4}
}

func (x *MangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *MangaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MangaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_mangahub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Manga               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_mangahub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResponse) GetItems() []*Manga {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Chapter       int32                  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Volume        int32                  `protobuf:"varint,4,opt,name=volume,proto3" json:"volume,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	Force         bool                   `protobuf:"varint,6,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_mangahub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{7}
}

func (x *ProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *ProgressRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *ProgressRequest) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *ProgressRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ProgressRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ProgressResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_mangahub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{8}
}

func (x *ProgressResponse) GetResult() *ProgressResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProgressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_mangahub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{9}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_mangahub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_mangahub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{11}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetLibraryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLibraryRequest) Reset() {
	*x = GetLibraryRequest{}
	mi := &file_mangahub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibraryRequest) ProtoMessage() {}

func (x *GetLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibraryRequest.ProtoReflect.Descriptor instead.
func (*GetLibraryRequest) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{12}
}

func (x *GetLibraryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LibraryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LibraryEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LibraryResponse) Reset() {
	*x = LibraryResponse{}
	mi := &file_mangahub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryResponse) ProtoMessage() {}

func (x *LibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mangahub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryResponse.ProtoReflect.Descriptor instead.
func (*LibraryResponse) Descriptor() ([]byte, []int) {
	return file_mangahub_proto_rawDescGZIP(), []int{13}
}

func (x *LibraryResponse) GetEntries() []*LibraryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LibraryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mangahub_proto protoreflect.FileDescriptor

const file_mangahub_proto_rawDesc = "" +
	"\n" +
	"\x0emangahub.proto\x12\bmangahub\"\xdb\x01\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x16\n" +
	"\x06genres\x18\x04 \x03(\tR\x06genres\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\x06 \x01(\x05R\rtotalChapters\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\b \x01(\tR\bcoverUrl\"\xee\x01\n" +
	"\fLibraryEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12'\n" +
	"\x0fcurrent_chapter\x18\x04 \x01(\x05R\x0ecurrentChapter\x12%\n" +
	"\x0ecurrent_volume\x18\x05 \x01(\x05R\rcurrentVolume\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06rating\x18\a \x01(\x05R\x06rating\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\"\xda\x01\n" +
	"\x0eProgressResult\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.mangahub.LibraryEntryR\x05entry\x12)\n" +
	"\x10previous_chapter\x18\x02 \x01(\x05R\x0fpreviousChapter\x12'\n" +
	"\x0fprevious_volume\x18\x03 \x01(\x05R\x0epreviousVolume\x12%\n" +
	"\x0etotal_chapters\x18\x04 \x01(\x05R\rtotalChapters\x12\x1f\n" +
	"\vmanga_title\x18\x05 \x01(\tR\n" +
	"mangaTitle\"!\n" +
	"\x0fGetMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"d\n" +
	"\rMangaResponse\x12%\n" +
	"\x05manga\x18\x01 \x01(\v2\x0f.mangahub.MangaR\x05manga\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\";\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"e\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.mangahub.MangaR\x05items\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa3\x01\n" +
	"\x0fProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x18\n" +
	"\achapter\x18\x03 \x01(\x05R\achapter\x12\x16\n" +
	"\x06volume\x18\x04 \x01(\x05R\x06volume\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\x12\x14\n" +
	"\x05force\x18\x06 \x01(\bR\x05force\"Z\n" +
	"\x10ProgressResponse\x120\n" +
	"\x06result\x18\x01 \x01(\v2\x18.mangahub.ProgressResultR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"g\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"E\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"H\n" +
	"\fUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.mangahub.UserR\x04user\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x11GetLibraryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Y\n" +
	"\x0fLibraryResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.mangahub.LibraryEntryR\aentries\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xd9\x01\n" +
	"\fMangaService\x12>\n" +
	"\bGetManga\x12\x19.mangahub.GetMangaRequest\x1a\x17.mangahub.MangaResponse\x12@\n" +
	"\vSearchManga\x12\x17.mangahub.SearchRequest\x1a\x18.mangahub.SearchResponse\x12G\n" +
	"\x0eUpdateProgress\x12\x19.mangahub.ProgressRequest\x1a\x1a.mangahub.ProgressResponse2\x90\x01\n" +
	"\vUserService\x12;\n" +
	"\aGetUser\x12\x18.mangahub.GetUserRequest\x1a\x16.mangahub.UserResponse\x12D\n" +
	"\n" +
	"GetLibrary\x12\x1b.mangahub.GetLibraryRequest\x1a\x19.mangahub.LibraryResponseB\x1eZ\x1cmangahub/internal/grpc/pb;pbb\x06proto3"

var (
	file_mangahub_proto_rawDescOnce sync.Once
	file_mangahub_proto_rawDescData []byte
)

func file_mangahub_proto_rawDescGZIP() []byte {
	file_mangahub_proto_rawDescOnce.Do(func() {
		file_mangahub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mangahub_proto_rawDesc), len(file_mangahub_proto_rawDesc)))
	})
	return file_mangahub_proto_rawDescData
}

var file_mangahub_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_mangahub_proto_goTypes = []any{
	(*Manga)(nil),             // 0: mangahub.Manga
	(*LibraryEntry)(nil),      // 1: mangahub.LibraryEntry
	(*ProgressResult)(nil),    // 2: mangahub.ProgressResult
	(*GetMangaRequest)(nil),   // 3: mangahub.GetMangaRequest
	(*MangaResponse)(nil),     // 4: mangahub.MangaResponse
	(*SearchRequest)(nil),     // 5: mangahub.SearchRequest
	(*SearchResponse)(nil),    // 6: mangahub.SearchResponse
	(*ProgressRequest)(nil),   // 7: mangahub.ProgressRequest
	(*ProgressResponse)(nil),  // 8: mangahub.ProgressResponse
	(*User)(nil),              // 9: mangahub.User
	(*GetUserRequest)(nil),    // 10: mangahub.GetUserRequest
	(*UserResponse)(nil),      // 11: mangahub.UserResponse
	(*GetLibraryRequest)(nil), // 12: mangahub.GetLibraryRequest
	(*LibraryResponse)(nil),   // 13: mangahub.LibraryResponse
}
var file_mangahub_proto_depIdxs = []int32{
	1,  // 0: mangahub.ProgressResult.entry:type_name -> mangahub.LibraryEntry
	0,  // 1: mangahub.MangaResponse.manga:type_name -> mangahub.Manga
	0,  // 2: mangahub.SearchResponse.items:type_name -> mangahub.Manga
	2,  // 3: mangahub.ProgressResponse.result:type_name -> mangahub.ProgressResult
	9,  // 4: mangahub.UserResponse.user:type_name -> mangahub.User
	1,  // 5: mangahub.LibraryResponse.entries:type_name -> mangahub.LibraryEntry
	3,  // 6: mangahub.MangaService.GetManga:input_type -> mangahub.GetMangaRequest
	5,  // 7: mangahub.MangaService.SearchManga:input_type -> mangahub.SearchRequest
	7,  // 8: mangahub.MangaService.UpdateProgress:input_type -> mangahub.ProgressRequest
	10, // 9: mangahub.UserService.GetUser:input_type -> mangahub.GetUserRequest
	12, // 10: mangahub.UserService.GetLibrary:input_type -> mangahub.GetLibraryRequest
	4,  // 11: mangahub.MangaService.GetManga:output_type -> mangahub.MangaResponse
	6,  // 12: mangahub.MangaService.SearchManga:output_type -> mangahub.SearchResponse
	8,  // 13: mangahub.MangaService.UpdateProgress:output_type -> mangahub.ProgressResponse
	11, // 14: mangahub.UserService.GetUser:output_type -> mangahub.UserResponse
	13, // 15: mangahub.UserService.GetLibrary:output_type -> mangahub.LibraryResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_mangahub_proto_init() }
func file_mangahub_proto_init() {
	if File_mangahub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mangahub_proto_rawDesc), len(file_mangahub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mangahub_proto_goTypes,
		DependencyIndexes: file_mangahub_proto_depIdxs,
		MessageInfos:      file_mangahub_proto_msgTypes,
	}.Build()
	File_mangahub_proto = out.File
	file_mangahub_proto_goTypes = nil
	file_mangahub_proto_depIdxs = nil
}
